- hosts: webservers
  become: yes
  tasks:
    - name: ensure apache is at the latest version
      yum:
        name: httpd
        state: latest
    - name: write the apache config file
      copy: 
        content: "Welcome To Ansible Class! \n"
        dest: /var/www/html/index.html
    
