---
- hosts: "controller"
  become: yes
  tasks:
    - name: install kustomization tool
      shell: |
        wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_linux_amd64.tar.gz
        tar xvz -f kustomize_v5.2.1_linux_amd64.tar.gz
        mv kustomize  /bin
    - name: creating yaml file
      shell: |
        cat > kustomization.yml << EOF
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
          - github.com/ansible/awx-operator/config/default?ref=2.7.2
        images:
          - name: quay.io/ansible/awx-operator
            newTag: 2.7.2
        namespace: awx
        EOF
    - name: applying the file
      shell: kubectl apply -k .
