---
- name: Configure containerd
  hosts: controller, workers
  become: true
  tasks:
    - name: Get PAUSE_IMAGE
      shell: "kubeadm config images list | grep pause"
      register: pause_image_raw

    - set_fact:
        pause_image: "{{ pause_image_raw.stdout_lines[0] | default('') }}"

    - name: Copy containerd default config
      copy:
        content: |
          [plugins."io.containerd.grpc.v1.cri".containerd]
            systemd_cgroup = true
            [plugins."io.containerd.grpc.v1.cri".sandbox]
              image = "{{ pause_image }}"
        dest: /etc/containerd/config.toml

    - name: Update PAUSE_IMAGE in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: 'sandbox_image = ".*"'
        replace: 'sandbox_image = "{{ pause_image }}"'
    - name: restart containerd service
      service:
        name: containerd
        state: restarted
    - name: restart kubelet
      service:
        name: kubelet
        state: restarted
