---
- name: configure SOE
  hosts: all
  become: true
  vars:
    system_owner: eyesoncloud
  tasks:
    - name: configure /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: admin
        group: wheel
        mode: 0664
